[package]
name = "cyber-patrol-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = "0.13"
aya-log = "0.2"
cyber-patrol-common = { path = "../cyber-patrol-common", features = ["user"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
libc = "0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }

[build-dependencies]
aya-build = "0.1"
cargo_metadata = "0.18"

[[bin]]
name = "cyber-patrol-loader"
path = "src/main.rs"
